# Site settings
title: Austin Copeman
email: contactme@austincopeman.com
url: https://www.austincopeman.com
description: "My personal website! This website contains all of my accomplishents, goals and projects that I have worked on throughout my career"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: www.austincopeman.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/austincopeman
  - title: google-plus
    url: https://plus.google.com/+AustinCopeman/posts
  - title: github
    url: https://github.com/acope

# Build settings
markdown: kramdown
permalink: pretty
